### ISSUE TITLE
neat_js压缩JS会导致部分网页效果失效

### ISSUE THREAD

**Issue by MoshiCoCo** [Rozbo/hexo-neat#10]
对部分js代码压缩会导致这部分js代码功能不正常。
当关闭neat_js选项压缩时则可以正常工作，我尝试用exclude选项跳过该文件 但是无法跳过 依旧时会出现问题。

1. 已知Valine评论会出现错误，关闭Neat则回复正常。可能是由于neat_js选项导致的
2. 其他的还比如我添加了一个页面点击 出现桃心的效果也失效，关闭neat_js 则正常
3. 友链下划线则会连再一起 关闭Neat_html则正常(页面布局，曾经出现一次页面混乱)
4. exclude的功能可能失效了，不知道是不是我的设置错误的原因
5. 其他的还比如我添加了一个页面点击 出现桃心的效果也失效，关闭neat_js 则正常
6. 还会导致canvas-nest背景动画工作不正常，F12提示unexpected token
经过对比发现canvas-nest.min.js文件多了下面一段。
`</0?-1:1,e.fillrect(i.x-0.5,i.y-0.5,1,1);for(v=0;v<w.length;v++){x=w[v];if(i!==x&&null!==x.x&&null!==x.y){b=i.x-x.x,z=i.y-x.y,y=b*b+z*z;y<x.max&&(x===f&&y></0?-1:1,i.ya*=i.y>`

第一次提Issues，如果需要更多信息，我再补充

附上插件列表
`  "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-neat": "^1.0.4",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-symbols-count-time": "^0.4.4"
`

**Comment by lewky** [comment]
@moshiyeap 其实是可以跳过的，只是你需要添加文件的路径，你可以用下边的写法来排除不希望被压缩的文件：
```
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'
```
