### ISSUE TITLE
exclude: '*.min.js' can not work 

### ISSUE THREAD

**Issue by lewky** [Rozbo/hexo-neat#11]
I found config '*.min.js' cannot work. Should add prefix path like '**/'. It can work in my hexo-Next theme as follows:
```
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
```
