### ISSUE TITLE
The way to exclude the some dir in hexo.

### ISSUE THREAD

**Issue by NewbMiao** [Rozbo/hexo-neat#2]
```
neat_enable: true
neat_html:
  enable: true
  exclude:
    - "**/dir/**"
    - "**/+(dir1|dir2)/**"

```
When i wanna exclude some dir in hexo, i find it worked out with the doc of `minimatch`.
Maybe help someone when use neat plugin.

Thks rozbo!
