### ISSUE TITLE
可否添加一个选项，仅删除空行

### ISSUE THREAD

**Issue by ljcbaby** [Rozbo/hexo-neat#20]
对于对于现有的形式，在git提交过程中，基本上相当于所有文件重写。这样的变更量太大，对于git来讲并不适。
如果仅仅是删除空行，这样就不至于造成文件重写，每次git同步的变化量也要小很多。

**Comment by ohroy** [comment]
目前已有此选项
```yaml
neat_html:
  enable: true
  exclude: null
  preserveLineBreaks: true # 此选项决定移除空白行时不进行行折叠
```
